###
POST http://localhost:3000/api/user HTTP/1.1
Content-Type: application/json

{
    "name": "Juan",
    "lastname": "Vega",
    "bank_account": "734",
    "address": {
        "city": "Medellin",
        "zip_code": 170001,
        "lat": -21000,
        "lon": 500
    }
}

###
GET http://localhost:3000/api/users HTTP/1.1

###
GET http://localhost:3000/api/users/6214487fafe9b32e106f0391 HTTP/1.1

###
DELETE http://localhost:3000/api/users/620e495b4c4fcccf125b2b2f HTTP/1.1

###
PUT http://localhost:3000/api/users/6214487fafe9b32e106f0391 HTTP/1.1
Content-Type: application/json

{
    "address": {
        "city": "Medellin"
    }
}

###
POST http://localhost:3000/api/products HTTP/1.1
Content-Type: application/json

{
    "product_name": "Book",
    "image": "./src/assets/images/books.jpg",
    "price": 20000,
    "quantity": 0,
    "avaiable": false
}

###
GET http://localhost:3000/api/products HTTP/1.1

###
GET http://localhost:3000/api/products/621451fc4a8d8beda824a156 HTTP/1.1

###
DELETE http://localhost:3000/api/products/621451fc4a8d8beda824a156 HTTP/1.1

###
PUT http://localhost:3000/api/products/621451fc4a8d8beda824a156
Content-Type: application/json

{
    "price": 100
}